server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java_study
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    username: rabbit
    password: qwesda
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
management:
    endpoints:
      web:
        exposure:
          include: [ "prometheus", "health" ]
