global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: actuator_prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'localhost:8080'
  - job_name: actuator_up
    metrics_path: /actuator/health
    static_configs:
      - targets:
          - 'localhost:8080'